/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityLogGet200ResponseActivityLogsInner } from './ActivityLogGet200ResponseActivityLogsInner';
import {
    ActivityLogGet200ResponseActivityLogsInnerFromJSON,
    ActivityLogGet200ResponseActivityLogsInnerFromJSONTyped,
    ActivityLogGet200ResponseActivityLogsInnerToJSON,
    ActivityLogGet200ResponseActivityLogsInnerToJSONTyped,
} from './ActivityLogGet200ResponseActivityLogsInner';

/**
 * 
 * @export
 * @interface ActivityLogIdGet200Response
 */
export interface ActivityLogIdGet200Response {
    /**
     * 
     * @type {ActivityLogGet200ResponseActivityLogsInner}
     * @memberof ActivityLogIdGet200Response
     */
    activityLog: ActivityLogGet200ResponseActivityLogsInner;
}

/**
 * Check if a given object implements the ActivityLogIdGet200Response interface.
 */
export function instanceOfActivityLogIdGet200Response(value: object): value is ActivityLogIdGet200Response {
    if (!('activityLog' in value) || value['activityLog'] === undefined) return false;
    return true;
}

export function ActivityLogIdGet200ResponseFromJSON(json: any): ActivityLogIdGet200Response {
    return ActivityLogIdGet200ResponseFromJSONTyped(json, false);
}

export function ActivityLogIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLogIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'activityLog': ActivityLogGet200ResponseActivityLogsInnerFromJSON(json['activity_log']),
    };
}

export function ActivityLogIdGet200ResponseToJSON(json: any): ActivityLogIdGet200Response {
    return ActivityLogIdGet200ResponseToJSONTyped(json, false);
}

export function ActivityLogIdGet200ResponseToJSONTyped(value?: ActivityLogIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activity_log': ActivityLogGet200ResponseActivityLogsInnerToJSON(value['activityLog']),
    };
}

