/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityLogGet200ResponseActivityLogsInner } from './ActivityLogGet200ResponseActivityLogsInner';
import {
    ActivityLogGet200ResponseActivityLogsInnerFromJSON,
    ActivityLogGet200ResponseActivityLogsInnerFromJSONTyped,
    ActivityLogGet200ResponseActivityLogsInnerToJSON,
    ActivityLogGet200ResponseActivityLogsInnerToJSONTyped,
} from './ActivityLogGet200ResponseActivityLogsInner';

/**
 * 
 * @export
 * @interface ActivityLogGet200Response
 */
export interface ActivityLogGet200Response {
    /**
     * 
     * @type {Array<ActivityLogGet200ResponseActivityLogsInner>}
     * @memberof ActivityLogGet200Response
     */
    activityLogs: Array<ActivityLogGet200ResponseActivityLogsInner>;
    /**
     * 
     * @type {number}
     * @memberof ActivityLogGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ActivityLogGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ActivityLogGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the ActivityLogGet200Response interface.
 */
export function instanceOfActivityLogGet200Response(value: object): value is ActivityLogGet200Response {
    if (!('activityLogs' in value) || value['activityLogs'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ActivityLogGet200ResponseFromJSON(json: any): ActivityLogGet200Response {
    return ActivityLogGet200ResponseFromJSONTyped(json, false);
}

export function ActivityLogGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLogGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'activityLogs': ((json['activity_logs'] as Array<any>).map(ActivityLogGet200ResponseActivityLogsInnerFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function ActivityLogGet200ResponseToJSON(json: any): ActivityLogGet200Response {
    return ActivityLogGet200ResponseToJSONTyped(json, false);
}

export function ActivityLogGet200ResponseToJSONTyped(value?: ActivityLogGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activity_logs': ((value['activityLogs'] as Array<any>).map(ActivityLogGet200ResponseActivityLogsInnerToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

