/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityLogPost200Response
 */
export interface ActivityLogPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ActivityLogPost200Response
     */
    logId: number;
}

/**
 * Check if a given object implements the ActivityLogPost200Response interface.
 */
export function instanceOfActivityLogPost200Response(value: object): value is ActivityLogPost200Response {
    if (!('logId' in value) || value['logId'] === undefined) return false;
    return true;
}

export function ActivityLogPost200ResponseFromJSON(json: any): ActivityLogPost200Response {
    return ActivityLogPost200ResponseFromJSONTyped(json, false);
}

export function ActivityLogPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLogPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'logId': json['log_id'],
    };
}

export function ActivityLogPost200ResponseToJSON(json: any): ActivityLogPost200Response {
    return ActivityLogPost200ResponseToJSONTyped(json, false);
}

export function ActivityLogPost200ResponseToJSONTyped(value?: ActivityLogPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'log_id': value['logId'],
    };
}

