/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityLogGet200ResponseActivityLogsInner
 */
export interface ActivityLogGet200ResponseActivityLogsInner {
    /**
     * 
     * @type {number}
     * @memberof ActivityLogGet200ResponseActivityLogsInner
     */
    logId: number;
    /**
     * 
     * @type {number}
     * @memberof ActivityLogGet200ResponseActivityLogsInner
     */
    machineId: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogGet200ResponseActivityLogsInner
     */
    message: string;
    /**
     * 
     * @type {Date}
     * @memberof ActivityLogGet200ResponseActivityLogsInner
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ActivityLogGet200ResponseActivityLogsInner interface.
 */
export function instanceOfActivityLogGet200ResponseActivityLogsInner(value: object): value is ActivityLogGet200ResponseActivityLogsInner {
    if (!('logId' in value) || value['logId'] === undefined) return false;
    if (!('machineId' in value) || value['machineId'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ActivityLogGet200ResponseActivityLogsInnerFromJSON(json: any): ActivityLogGet200ResponseActivityLogsInner {
    return ActivityLogGet200ResponseActivityLogsInnerFromJSONTyped(json, false);
}

export function ActivityLogGet200ResponseActivityLogsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLogGet200ResponseActivityLogsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'logId': json['log_id'],
        'machineId': json['machine_id'],
        'message': json['message'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ActivityLogGet200ResponseActivityLogsInnerToJSON(json: any): ActivityLogGet200ResponseActivityLogsInner {
    return ActivityLogGet200ResponseActivityLogsInnerToJSONTyped(json, false);
}

export function ActivityLogGet200ResponseActivityLogsInnerToJSONTyped(value?: ActivityLogGet200ResponseActivityLogsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'log_id': value['logId'],
        'machine_id': value['machineId'],
        'message': value['message'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

