/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityLogPostRequest
 */
export interface ActivityLogPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ActivityLogPostRequest
     */
    machineId: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogPostRequest
     */
    message: string;
    /**
     * 
     * @type {Date}
     * @memberof ActivityLogPostRequest
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ActivityLogPostRequest interface.
 */
export function instanceOfActivityLogPostRequest(value: object): value is ActivityLogPostRequest {
    if (!('machineId' in value) || value['machineId'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ActivityLogPostRequestFromJSON(json: any): ActivityLogPostRequest {
    return ActivityLogPostRequestFromJSONTyped(json, false);
}

export function ActivityLogPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLogPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'machineId': json['machine_id'],
        'message': json['message'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ActivityLogPostRequestToJSON(json: any): ActivityLogPostRequest {
    return ActivityLogPostRequestToJSONTyped(json, false);
}

export function ActivityLogPostRequestToJSONTyped(value?: ActivityLogPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machine_id': value['machineId'],
        'message': value['message'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

