/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiPostRequest
 */
export interface AiPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AiPostRequest
     */
    message: string;
}

/**
 * Check if a given object implements the AiPostRequest interface.
 */
export function instanceOfAiPostRequest(value: object): value is AiPostRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AiPostRequestFromJSON(json: any): AiPostRequest {
    return AiPostRequestFromJSONTyped(json, false);
}

export function AiPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function AiPostRequestToJSON(json: any): AiPostRequest {
    return AiPostRequestToJSONTyped(json, false);
}

export function AiPostRequestToJSONTyped(value?: AiPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

