/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttributePost200Response
 */
export interface AttributePost200Response {
    /**
     * 
     * @type {number}
     * @memberof AttributePost200Response
     */
    attributeId: number;
}

/**
 * Check if a given object implements the AttributePost200Response interface.
 */
export function instanceOfAttributePost200Response(value: object): value is AttributePost200Response {
    if (!('attributeId' in value) || value['attributeId'] === undefined) return false;
    return true;
}

export function AttributePost200ResponseFromJSON(json: any): AttributePost200Response {
    return AttributePost200ResponseFromJSONTyped(json, false);
}

export function AttributePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'attributeId': json['attribute_id'],
    };
}

export function AttributePost200ResponseToJSON(json: any): AttributePost200Response {
    return AttributePost200ResponseToJSONTyped(json, false);
}

export function AttributePost200ResponseToJSONTyped(value?: AttributePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribute_id': value['attributeId'],
    };
}

