/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttributeGet200ResponseAttributesInner
 */
export interface AttributeGet200ResponseAttributesInner {
    /**
     * 
     * @type {number}
     * @memberof AttributeGet200ResponseAttributesInner
     */
    attributeId: number;
    /**
     * 
     * @type {string}
     * @memberof AttributeGet200ResponseAttributesInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeGet200ResponseAttributesInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeGet200ResponseAttributesInner
     */
    unit: string | null;
}

/**
 * Check if a given object implements the AttributeGet200ResponseAttributesInner interface.
 */
export function instanceOfAttributeGet200ResponseAttributesInner(value: object): value is AttributeGet200ResponseAttributesInner {
    if (!('attributeId' in value) || value['attributeId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function AttributeGet200ResponseAttributesInnerFromJSON(json: any): AttributeGet200ResponseAttributesInner {
    return AttributeGet200ResponseAttributesInnerFromJSONTyped(json, false);
}

export function AttributeGet200ResponseAttributesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeGet200ResponseAttributesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'attributeId': json['attribute_id'],
        'name': json['name'],
        'type': json['type'],
        'unit': json['unit'],
    };
}

export function AttributeGet200ResponseAttributesInnerToJSON(json: any): AttributeGet200ResponseAttributesInner {
    return AttributeGet200ResponseAttributesInnerToJSONTyped(json, false);
}

export function AttributeGet200ResponseAttributesInnerToJSONTyped(value?: AttributeGet200ResponseAttributesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribute_id': value['attributeId'],
        'name': value['name'],
        'type': value['type'],
        'unit': value['unit'],
    };
}

