/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttributePostRequest
 */
export interface AttributePostRequest {
    /**
     * 
     * @type {string}
     * @memberof AttributePostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AttributePostRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AttributePostRequest
     */
    unit: string | null;
}

/**
 * Check if a given object implements the AttributePostRequest interface.
 */
export function instanceOfAttributePostRequest(value: object): value is AttributePostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function AttributePostRequestFromJSON(json: any): AttributePostRequest {
    return AttributePostRequestFromJSONTyped(json, false);
}

export function AttributePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'unit': json['unit'],
    };
}

export function AttributePostRequestToJSON(json: any): AttributePostRequest {
    return AttributePostRequestToJSONTyped(json, false);
}

export function AttributePostRequestToJSONTyped(value?: AttributePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'unit': value['unit'],
    };
}

