/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeGet200ResponseAttributesInner } from './AttributeGet200ResponseAttributesInner';
import {
    AttributeGet200ResponseAttributesInnerFromJSON,
    AttributeGet200ResponseAttributesInnerFromJSONTyped,
    AttributeGet200ResponseAttributesInnerToJSON,
    AttributeGet200ResponseAttributesInnerToJSONTyped,
} from './AttributeGet200ResponseAttributesInner';

/**
 * 
 * @export
 * @interface AttributeGet200Response
 */
export interface AttributeGet200Response {
    /**
     * 
     * @type {Array<AttributeGet200ResponseAttributesInner>}
     * @memberof AttributeGet200Response
     */
    attributes: Array<AttributeGet200ResponseAttributesInner>;
    /**
     * 
     * @type {number}
     * @memberof AttributeGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof AttributeGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof AttributeGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the AttributeGet200Response interface.
 */
export function instanceOfAttributeGet200Response(value: object): value is AttributeGet200Response {
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function AttributeGet200ResponseFromJSON(json: any): AttributeGet200Response {
    return AttributeGet200ResponseFromJSONTyped(json, false);
}

export function AttributeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': ((json['attributes'] as Array<any>).map(AttributeGet200ResponseAttributesInnerFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function AttributeGet200ResponseToJSON(json: any): AttributeGet200Response {
    return AttributeGet200ResponseToJSONTyped(json, false);
}

export function AttributeGet200ResponseToJSONTyped(value?: AttributeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': ((value['attributes'] as Array<any>).map(AttributeGet200ResponseAttributesInnerToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

