/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeGet200ResponseAttributesInner } from './AttributeGet200ResponseAttributesInner';
import {
    AttributeGet200ResponseAttributesInnerFromJSON,
    AttributeGet200ResponseAttributesInnerFromJSONTyped,
    AttributeGet200ResponseAttributesInnerToJSON,
    AttributeGet200ResponseAttributesInnerToJSONTyped,
} from './AttributeGet200ResponseAttributesInner';

/**
 * 
 * @export
 * @interface AttributeIdGet200Response
 */
export interface AttributeIdGet200Response {
    /**
     * 
     * @type {AttributeGet200ResponseAttributesInner}
     * @memberof AttributeIdGet200Response
     */
    attribute: AttributeGet200ResponseAttributesInner;
}

/**
 * Check if a given object implements the AttributeIdGet200Response interface.
 */
export function instanceOfAttributeIdGet200Response(value: object): value is AttributeIdGet200Response {
    if (!('attribute' in value) || value['attribute'] === undefined) return false;
    return true;
}

export function AttributeIdGet200ResponseFromJSON(json: any): AttributeIdGet200Response {
    return AttributeIdGet200ResponseFromJSONTyped(json, false);
}

export function AttributeIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'attribute': AttributeGet200ResponseAttributesInnerFromJSON(json['attribute']),
    };
}

export function AttributeIdGet200ResponseToJSON(json: any): AttributeIdGet200Response {
    return AttributeIdGet200ResponseToJSONTyped(json, false);
}

export function AttributeIdGet200ResponseToJSONTyped(value?: AttributeIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribute': AttributeGet200ResponseAttributesInnerToJSON(value['attribute']),
    };
}

