/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginPostRequest
 */
export interface AuthLoginPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AuthLoginPostRequest interface.
 */
export function instanceOfAuthLoginPostRequest(value: object): value is AuthLoginPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthLoginPostRequestFromJSON(json: any): AuthLoginPostRequest {
    return AuthLoginPostRequestFromJSONTyped(json, false);
}

export function AuthLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthLoginPostRequestToJSON(json: any): AuthLoginPostRequest {
    return AuthLoginPostRequestToJSONTyped(json, false);
}

export function AuthLoginPostRequestToJSONTyped(value?: AuthLoginPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

