/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRegisterPostRequest
 */
export interface AuthRegisterPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterPostRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AuthRegisterPostRequest interface.
 */
export function instanceOfAuthRegisterPostRequest(value: object): value is AuthRegisterPostRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthRegisterPostRequestFromJSON(json: any): AuthRegisterPostRequest {
    return AuthRegisterPostRequestFromJSONTyped(json, false);
}

export function AuthRegisterPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthRegisterPostRequestToJSON(json: any): AuthRegisterPostRequest {
    return AuthRegisterPostRequestToJSONTyped(json, false);
}

export function AuthRegisterPostRequestToJSONTyped(value?: AuthRegisterPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'email': value['email'],
        'password': value['password'],
    };
}

