/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRegisterPost201Response
 */
export interface AuthRegisterPost201Response {
    /**
     * 
     * @type {number}
     * @memberof AuthRegisterPost201Response
     */
    userId: number;
}

/**
 * Check if a given object implements the AuthRegisterPost201Response interface.
 */
export function instanceOfAuthRegisterPost201Response(value: object): value is AuthRegisterPost201Response {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AuthRegisterPost201ResponseFromJSON(json: any): AuthRegisterPost201Response {
    return AuthRegisterPost201ResponseFromJSONTyped(json, false);
}

export function AuthRegisterPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
    };
}

export function AuthRegisterPost201ResponseToJSON(json: any): AuthRegisterPost201Response {
    return AuthRegisterPost201ResponseToJSONTyped(json, false);
}

export function AuthRegisterPost201ResponseToJSONTyped(value?: AuthRegisterPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

