/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginPost401Response
 */
export interface AuthLoginPost401Response {
    /**
     * 
     * @type {number}
     * @memberof AuthLoginPost401Response
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost401Response
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost401Response
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost401Response
     */
    message: string;
}

/**
 * Check if a given object implements the AuthLoginPost401Response interface.
 */
export function instanceOfAuthLoginPost401Response(value: object): value is AuthLoginPost401Response {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AuthLoginPost401ResponseFromJSON(json: any): AuthLoginPost401Response {
    return AuthLoginPost401ResponseFromJSONTyped(json, false);
}

export function AuthLoginPost401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPost401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'code': json['code'],
        'error': json['error'],
        'message': json['message'],
    };
}

export function AuthLoginPost401ResponseToJSON(json: any): AuthLoginPost401Response {
    return AuthLoginPost401ResponseToJSONTyped(json, false);
}

export function AuthLoginPost401ResponseToJSONTyped(value?: AuthLoginPost401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'code': value['code'],
        'error': value['error'],
        'message': value['message'],
    };
}

