/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocateGet200ResponseLocationsInner } from './LocateGet200ResponseLocationsInner';
import {
    LocateGet200ResponseLocationsInnerFromJSON,
    LocateGet200ResponseLocationsInnerFromJSONTyped,
    LocateGet200ResponseLocationsInnerToJSON,
    LocateGet200ResponseLocationsInnerToJSONTyped,
} from './LocateGet200ResponseLocationsInner';

/**
 * 
 * @export
 * @interface LocateIdGet200Response
 */
export interface LocateIdGet200Response {
    /**
     * 
     * @type {LocateGet200ResponseLocationsInner}
     * @memberof LocateIdGet200Response
     */
    location: LocateGet200ResponseLocationsInner;
}

/**
 * Check if a given object implements the LocateIdGet200Response interface.
 */
export function instanceOfLocateIdGet200Response(value: object): value is LocateIdGet200Response {
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function LocateIdGet200ResponseFromJSON(json: any): LocateIdGet200Response {
    return LocateIdGet200ResponseFromJSONTyped(json, false);
}

export function LocateIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocateIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'location': LocateGet200ResponseLocationsInnerFromJSON(json['location']),
    };
}

export function LocateIdGet200ResponseToJSON(json: any): LocateIdGet200Response {
    return LocateIdGet200ResponseToJSONTyped(json, false);
}

export function LocateIdGet200ResponseToJSONTyped(value?: LocateIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'location': LocateGet200ResponseLocationsInnerToJSON(value['location']),
    };
}

