/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocatePostRequest
 */
export interface LocatePostRequest {
    /**
     * 
     * @type {string}
     * @memberof LocatePostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LocatePostRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof LocatePostRequest
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof LocatePostRequest
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof LocatePostRequest
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof LocatePostRequest
     */
    zip: string;
    /**
     * 
     * @type {number}
     * @memberof LocatePostRequest
     */
    latitude: number | null;
    /**
     * 
     * @type {number}
     * @memberof LocatePostRequest
     */
    longitude: number | null;
}

/**
 * Check if a given object implements the LocatePostRequest interface.
 */
export function instanceOfLocatePostRequest(value: object): value is LocatePostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('zip' in value) || value['zip'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function LocatePostRequestFromJSON(json: any): LocatePostRequest {
    return LocatePostRequestFromJSONTyped(json, false);
}

export function LocatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'address': json['address'],
        'city': json['city'],
        'state': json['state'],
        'zip': json['zip'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function LocatePostRequestToJSON(json: any): LocatePostRequest {
    return LocatePostRequestToJSONTyped(json, false);
}

export function LocatePostRequestToJSONTyped(value?: LocatePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'address': value['address'],
        'city': value['city'],
        'state': value['state'],
        'zip': value['zip'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

