/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MachineTypePostRequest
 */
export interface MachineTypePostRequest {
    /**
     * 
     * @type {string}
     * @memberof MachineTypePostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MachineTypePostRequest
     */
    description: string | null;
}

/**
 * Check if a given object implements the MachineTypePostRequest interface.
 */
export function instanceOfMachineTypePostRequest(value: object): value is MachineTypePostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function MachineTypePostRequestFromJSON(json: any): MachineTypePostRequest {
    return MachineTypePostRequestFromJSONTyped(json, false);
}

export function MachineTypePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineTypePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function MachineTypePostRequestToJSON(json: any): MachineTypePostRequest {
    return MachineTypePostRequestToJSONTyped(json, false);
}

export function MachineTypePostRequestToJSONTyped(value?: MachineTypePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

