/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MachineTypeGet200ResponseMachineTypesInner
 */
export interface MachineTypeGet200ResponseMachineTypesInner {
    /**
     * 
     * @type {number}
     * @memberof MachineTypeGet200ResponseMachineTypesInner
     */
    machineTypeId: number;
    /**
     * 
     * @type {string}
     * @memberof MachineTypeGet200ResponseMachineTypesInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MachineTypeGet200ResponseMachineTypesInner
     */
    description: string | null;
}

/**
 * Check if a given object implements the MachineTypeGet200ResponseMachineTypesInner interface.
 */
export function instanceOfMachineTypeGet200ResponseMachineTypesInner(value: object): value is MachineTypeGet200ResponseMachineTypesInner {
    if (!('machineTypeId' in value) || value['machineTypeId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function MachineTypeGet200ResponseMachineTypesInnerFromJSON(json: any): MachineTypeGet200ResponseMachineTypesInner {
    return MachineTypeGet200ResponseMachineTypesInnerFromJSONTyped(json, false);
}

export function MachineTypeGet200ResponseMachineTypesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineTypeGet200ResponseMachineTypesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'machineTypeId': json['machine_type_id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function MachineTypeGet200ResponseMachineTypesInnerToJSON(json: any): MachineTypeGet200ResponseMachineTypesInner {
    return MachineTypeGet200ResponseMachineTypesInnerToJSONTyped(json, false);
}

export function MachineTypeGet200ResponseMachineTypesInnerToJSONTyped(value?: MachineTypeGet200ResponseMachineTypesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machine_type_id': value['machineTypeId'],
        'name': value['name'],
        'description': value['description'],
    };
}

