/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MachinePost200Response
 */
export interface MachinePost200Response {
    /**
     * 
     * @type {number}
     * @memberof MachinePost200Response
     */
    machineId: number;
}

/**
 * Check if a given object implements the MachinePost200Response interface.
 */
export function instanceOfMachinePost200Response(value: object): value is MachinePost200Response {
    if (!('machineId' in value) || value['machineId'] === undefined) return false;
    return true;
}

export function MachinePost200ResponseFromJSON(json: any): MachinePost200Response {
    return MachinePost200ResponseFromJSONTyped(json, false);
}

export function MachinePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachinePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'machineId': json['machine_id'],
    };
}

export function MachinePost200ResponseToJSON(json: any): MachinePost200Response {
    return MachinePost200ResponseToJSONTyped(json, false);
}

export function MachinePost200ResponseToJSONTyped(value?: MachinePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machine_id': value['machineId'],
    };
}

