/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MachineGet200ResponseMachinesInner } from './MachineGet200ResponseMachinesInner';
import {
    MachineGet200ResponseMachinesInnerFromJSON,
    MachineGet200ResponseMachinesInnerFromJSONTyped,
    MachineGet200ResponseMachinesInnerToJSON,
    MachineGet200ResponseMachinesInnerToJSONTyped,
} from './MachineGet200ResponseMachinesInner';

/**
 * 
 * @export
 * @interface MachineGet200Response
 */
export interface MachineGet200Response {
    /**
     * 
     * @type {Array<MachineGet200ResponseMachinesInner>}
     * @memberof MachineGet200Response
     */
    machines: Array<MachineGet200ResponseMachinesInner>;
    /**
     * 
     * @type {number}
     * @memberof MachineGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof MachineGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof MachineGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the MachineGet200Response interface.
 */
export function instanceOfMachineGet200Response(value: object): value is MachineGet200Response {
    if (!('machines' in value) || value['machines'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function MachineGet200ResponseFromJSON(json: any): MachineGet200Response {
    return MachineGet200ResponseFromJSONTyped(json, false);
}

export function MachineGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'machines': ((json['machines'] as Array<any>).map(MachineGet200ResponseMachinesInnerFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function MachineGet200ResponseToJSON(json: any): MachineGet200Response {
    return MachineGet200ResponseToJSONTyped(json, false);
}

export function MachineGet200ResponseToJSONTyped(value?: MachineGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machines': ((value['machines'] as Array<any>).map(MachineGet200ResponseMachinesInnerToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

