/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MachinePostRequest
 */
export interface MachinePostRequest {
    /**
     * 
     * @type {string}
     * @memberof MachinePostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MachinePostRequest
     */
    description: string | null;
    /**
     * 
     * @type {number}
     * @memberof MachinePostRequest
     */
    machineTypeId: number;
    /**
     * 
     * @type {number}
     * @memberof MachinePostRequest
     */
    locationId: number;
}

/**
 * Check if a given object implements the MachinePostRequest interface.
 */
export function instanceOfMachinePostRequest(value: object): value is MachinePostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('machineTypeId' in value) || value['machineTypeId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    return true;
}

export function MachinePostRequestFromJSON(json: any): MachinePostRequest {
    return MachinePostRequestFromJSONTyped(json, false);
}

export function MachinePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachinePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'machineTypeId': json['machine_type_id'],
        'locationId': json['location_id'],
    };
}

export function MachinePostRequestToJSON(json: any): MachinePostRequest {
    return MachinePostRequestToJSONTyped(json, false);
}

export function MachinePostRequestToJSONTyped(value?: MachinePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'machine_type_id': value['machineTypeId'],
        'location_id': value['locationId'],
    };
}

