/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MachineGet200ResponseMachinesInner } from './MachineGet200ResponseMachinesInner';
import {
    MachineGet200ResponseMachinesInnerFromJSON,
    MachineGet200ResponseMachinesInnerFromJSONTyped,
    MachineGet200ResponseMachinesInnerToJSON,
    MachineGet200ResponseMachinesInnerToJSONTyped,
} from './MachineGet200ResponseMachinesInner';

/**
 * 
 * @export
 * @interface MachineIdGet200Response
 */
export interface MachineIdGet200Response {
    /**
     * 
     * @type {MachineGet200ResponseMachinesInner}
     * @memberof MachineIdGet200Response
     */
    machine: MachineGet200ResponseMachinesInner;
}

/**
 * Check if a given object implements the MachineIdGet200Response interface.
 */
export function instanceOfMachineIdGet200Response(value: object): value is MachineIdGet200Response {
    if (!('machine' in value) || value['machine'] === undefined) return false;
    return true;
}

export function MachineIdGet200ResponseFromJSON(json: any): MachineIdGet200Response {
    return MachineIdGet200ResponseFromJSONTyped(json, false);
}

export function MachineIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'machine': MachineGet200ResponseMachinesInnerFromJSON(json['machine']),
    };
}

export function MachineIdGet200ResponseToJSON(json: any): MachineIdGet200Response {
    return MachineIdGet200ResponseToJSONTyped(json, false);
}

export function MachineIdGet200ResponseToJSONTyped(value?: MachineIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machine': MachineGet200ResponseMachinesInnerToJSON(value['machine']),
    };
}

