/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MachineGet200ResponseMachinesInner
 */
export interface MachineGet200ResponseMachinesInner {
    /**
     * 
     * @type {number}
     * @memberof MachineGet200ResponseMachinesInner
     */
    machineId: number;
    /**
     * 
     * @type {string}
     * @memberof MachineGet200ResponseMachinesInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MachineGet200ResponseMachinesInner
     */
    description: string | null;
    /**
     * 
     * @type {number}
     * @memberof MachineGet200ResponseMachinesInner
     */
    machineTypeId: number;
    /**
     * 
     * @type {number}
     * @memberof MachineGet200ResponseMachinesInner
     */
    locationId: number;
    /**
     * 
     * @type {Date}
     * @memberof MachineGet200ResponseMachinesInner
     */
    lastUpdated: Date;
    /**
     * 
     * @type {Date}
     * @memberof MachineGet200ResponseMachinesInner
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the MachineGet200ResponseMachinesInner interface.
 */
export function instanceOfMachineGet200ResponseMachinesInner(value: object): value is MachineGet200ResponseMachinesInner {
    if (!('machineId' in value) || value['machineId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('machineTypeId' in value) || value['machineTypeId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function MachineGet200ResponseMachinesInnerFromJSON(json: any): MachineGet200ResponseMachinesInner {
    return MachineGet200ResponseMachinesInnerFromJSONTyped(json, false);
}

export function MachineGet200ResponseMachinesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineGet200ResponseMachinesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'machineId': json['machine_id'],
        'name': json['name'],
        'description': json['description'],
        'machineTypeId': json['machine_type_id'],
        'locationId': json['location_id'],
        'lastUpdated': (new Date(json['last_updated'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function MachineGet200ResponseMachinesInnerToJSON(json: any): MachineGet200ResponseMachinesInner {
    return MachineGet200ResponseMachinesInnerToJSONTyped(json, false);
}

export function MachineGet200ResponseMachinesInnerToJSONTyped(value?: MachineGet200ResponseMachinesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machine_id': value['machineId'],
        'name': value['name'],
        'description': value['description'],
        'machine_type_id': value['machineTypeId'],
        'location_id': value['locationId'],
        'last_updated': ((value['lastUpdated']).toISOString()),
        'created_at': ((value['createdAt']).toISOString()),
    };
}

