/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MachineTypeGet200ResponseMachineTypesInner } from './MachineTypeGet200ResponseMachineTypesInner';
import {
    MachineTypeGet200ResponseMachineTypesInnerFromJSON,
    MachineTypeGet200ResponseMachineTypesInnerFromJSONTyped,
    MachineTypeGet200ResponseMachineTypesInnerToJSON,
    MachineTypeGet200ResponseMachineTypesInnerToJSONTyped,
} from './MachineTypeGet200ResponseMachineTypesInner';

/**
 * 
 * @export
 * @interface MachineTypeIdGet200Response
 */
export interface MachineTypeIdGet200Response {
    /**
     * 
     * @type {MachineTypeGet200ResponseMachineTypesInner}
     * @memberof MachineTypeIdGet200Response
     */
    machineType: MachineTypeGet200ResponseMachineTypesInner;
}

/**
 * Check if a given object implements the MachineTypeIdGet200Response interface.
 */
export function instanceOfMachineTypeIdGet200Response(value: object): value is MachineTypeIdGet200Response {
    if (!('machineType' in value) || value['machineType'] === undefined) return false;
    return true;
}

export function MachineTypeIdGet200ResponseFromJSON(json: any): MachineTypeIdGet200Response {
    return MachineTypeIdGet200ResponseFromJSONTyped(json, false);
}

export function MachineTypeIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineTypeIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'machineType': MachineTypeGet200ResponseMachineTypesInnerFromJSON(json['machine_type']),
    };
}

export function MachineTypeIdGet200ResponseToJSON(json: any): MachineTypeIdGet200Response {
    return MachineTypeIdGet200ResponseToJSONTyped(json, false);
}

export function MachineTypeIdGet200ResponseToJSONTyped(value?: MachineTypeIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machine_type': MachineTypeGet200ResponseMachineTypesInnerToJSON(value['machineType']),
    };
}

