/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MachineTypeGet200ResponseMachineTypesInner } from './MachineTypeGet200ResponseMachineTypesInner';
import {
    MachineTypeGet200ResponseMachineTypesInnerFromJSON,
    MachineTypeGet200ResponseMachineTypesInnerFromJSONTyped,
    MachineTypeGet200ResponseMachineTypesInnerToJSON,
    MachineTypeGet200ResponseMachineTypesInnerToJSONTyped,
} from './MachineTypeGet200ResponseMachineTypesInner';

/**
 * 
 * @export
 * @interface MachineTypeGet200Response
 */
export interface MachineTypeGet200Response {
    /**
     * 
     * @type {Array<MachineTypeGet200ResponseMachineTypesInner>}
     * @memberof MachineTypeGet200Response
     */
    machineTypes: Array<MachineTypeGet200ResponseMachineTypesInner>;
    /**
     * 
     * @type {number}
     * @memberof MachineTypeGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof MachineTypeGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof MachineTypeGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the MachineTypeGet200Response interface.
 */
export function instanceOfMachineTypeGet200Response(value: object): value is MachineTypeGet200Response {
    if (!('machineTypes' in value) || value['machineTypes'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function MachineTypeGet200ResponseFromJSON(json: any): MachineTypeGet200Response {
    return MachineTypeGet200ResponseFromJSONTyped(json, false);
}

export function MachineTypeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineTypeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'machineTypes': ((json['machine_types'] as Array<any>).map(MachineTypeGet200ResponseMachineTypesInnerFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function MachineTypeGet200ResponseToJSON(json: any): MachineTypeGet200Response {
    return MachineTypeGet200ResponseToJSONTyped(json, false);
}

export function MachineTypeGet200ResponseToJSONTyped(value?: MachineTypeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machine_types': ((value['machineTypes'] as Array<any>).map(MachineTypeGet200ResponseMachineTypesInnerToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

