/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionGet200ResponsePermissionsInner } from './PermissionGet200ResponsePermissionsInner';
import {
    PermissionGet200ResponsePermissionsInnerFromJSON,
    PermissionGet200ResponsePermissionsInnerFromJSONTyped,
    PermissionGet200ResponsePermissionsInnerToJSON,
    PermissionGet200ResponsePermissionsInnerToJSONTyped,
} from './PermissionGet200ResponsePermissionsInner';

/**
 * 
 * @export
 * @interface PermissionIdGet200Response
 */
export interface PermissionIdGet200Response {
    /**
     * 
     * @type {PermissionGet200ResponsePermissionsInner}
     * @memberof PermissionIdGet200Response
     */
    permission: PermissionGet200ResponsePermissionsInner;
}

/**
 * Check if a given object implements the PermissionIdGet200Response interface.
 */
export function instanceOfPermissionIdGet200Response(value: object): value is PermissionIdGet200Response {
    if (!('permission' in value) || value['permission'] === undefined) return false;
    return true;
}

export function PermissionIdGet200ResponseFromJSON(json: any): PermissionIdGet200Response {
    return PermissionIdGet200ResponseFromJSONTyped(json, false);
}

export function PermissionIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'permission': PermissionGet200ResponsePermissionsInnerFromJSON(json['permission']),
    };
}

export function PermissionIdGet200ResponseToJSON(json: any): PermissionIdGet200Response {
    return PermissionIdGet200ResponseToJSONTyped(json, false);
}

export function PermissionIdGet200ResponseToJSONTyped(value?: PermissionIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permission': PermissionGet200ResponsePermissionsInnerToJSON(value['permission']),
    };
}

