/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionGet200ResponsePermissionsInner } from './PermissionGet200ResponsePermissionsInner';
import {
    PermissionGet200ResponsePermissionsInnerFromJSON,
    PermissionGet200ResponsePermissionsInnerFromJSONTyped,
    PermissionGet200ResponsePermissionsInnerToJSON,
    PermissionGet200ResponsePermissionsInnerToJSONTyped,
} from './PermissionGet200ResponsePermissionsInner';

/**
 * 
 * @export
 * @interface PermissionGet200Response
 */
export interface PermissionGet200Response {
    /**
     * 
     * @type {Array<PermissionGet200ResponsePermissionsInner>}
     * @memberof PermissionGet200Response
     */
    permissions: Array<PermissionGet200ResponsePermissionsInner>;
    /**
     * 
     * @type {number}
     * @memberof PermissionGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PermissionGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PermissionGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the PermissionGet200Response interface.
 */
export function instanceOfPermissionGet200Response(value: object): value is PermissionGet200Response {
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function PermissionGet200ResponseFromJSON(json: any): PermissionGet200Response {
    return PermissionGet200ResponseFromJSONTyped(json, false);
}

export function PermissionGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'permissions': ((json['permissions'] as Array<any>).map(PermissionGet200ResponsePermissionsInnerFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function PermissionGet200ResponseToJSON(json: any): PermissionGet200Response {
    return PermissionGet200ResponseToJSONTyped(json, false);
}

export function PermissionGet200ResponseToJSONTyped(value?: PermissionGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permissions': ((value['permissions'] as Array<any>).map(PermissionGet200ResponsePermissionsInnerToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

