/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionPost200Response
 */
export interface PermissionPost200Response {
    /**
     * 
     * @type {string}
     * @memberof PermissionPost200Response
     */
    permissionId: string;
}

/**
 * Check if a given object implements the PermissionPost200Response interface.
 */
export function instanceOfPermissionPost200Response(value: object): value is PermissionPost200Response {
    if (!('permissionId' in value) || value['permissionId'] === undefined) return false;
    return true;
}

export function PermissionPost200ResponseFromJSON(json: any): PermissionPost200Response {
    return PermissionPost200ResponseFromJSONTyped(json, false);
}

export function PermissionPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'permissionId': json['permission_id'],
    };
}

export function PermissionPost200ResponseToJSON(json: any): PermissionPost200Response {
    return PermissionPost200ResponseToJSONTyped(json, false);
}

export function PermissionPost200ResponseToJSONTyped(value?: PermissionPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permission_id': value['permissionId'],
    };
}

