/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionGet200ResponsePermissionsInner
 */
export interface PermissionGet200ResponsePermissionsInner {
    /**
     * 
     * @type {number}
     * @memberof PermissionGet200ResponsePermissionsInner
     */
    permissionId: number;
    /**
     * 
     * @type {string}
     * @memberof PermissionGet200ResponsePermissionsInner
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionGet200ResponsePermissionsInner
     */
    description: string | null;
}

/**
 * Check if a given object implements the PermissionGet200ResponsePermissionsInner interface.
 */
export function instanceOfPermissionGet200ResponsePermissionsInner(value: object): value is PermissionGet200ResponsePermissionsInner {
    if (!('permissionId' in value) || value['permissionId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function PermissionGet200ResponsePermissionsInnerFromJSON(json: any): PermissionGet200ResponsePermissionsInner {
    return PermissionGet200ResponsePermissionsInnerFromJSONTyped(json, false);
}

export function PermissionGet200ResponsePermissionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionGet200ResponsePermissionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'permissionId': json['permission_id'],
        'title': json['title'],
        'description': json['description'],
    };
}

export function PermissionGet200ResponsePermissionsInnerToJSON(json: any): PermissionGet200ResponsePermissionsInner {
    return PermissionGet200ResponsePermissionsInnerToJSONTyped(json, false);
}

export function PermissionGet200ResponsePermissionsInnerToJSONTyped(value?: PermissionGet200ResponsePermissionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permission_id': value['permissionId'],
        'title': value['title'],
        'description': value['description'],
    };
}

