/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReadingGet200ResponseReadingsInner } from './ReadingGet200ResponseReadingsInner';
import {
    ReadingGet200ResponseReadingsInnerFromJSON,
    ReadingGet200ResponseReadingsInnerFromJSONTyped,
    ReadingGet200ResponseReadingsInnerToJSON,
    ReadingGet200ResponseReadingsInnerToJSONTyped,
} from './ReadingGet200ResponseReadingsInner';

/**
 * 
 * @export
 * @interface ReadingGet200Response
 */
export interface ReadingGet200Response {
    /**
     * 
     * @type {Array<ReadingGet200ResponseReadingsInner>}
     * @memberof ReadingGet200Response
     */
    readings: Array<ReadingGet200ResponseReadingsInner>;
    /**
     * 
     * @type {number}
     * @memberof ReadingGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ReadingGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ReadingGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the ReadingGet200Response interface.
 */
export function instanceOfReadingGet200Response(value: object): value is ReadingGet200Response {
    if (!('readings' in value) || value['readings'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ReadingGet200ResponseFromJSON(json: any): ReadingGet200Response {
    return ReadingGet200ResponseFromJSONTyped(json, false);
}

export function ReadingGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadingGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'readings': ((json['readings'] as Array<any>).map(ReadingGet200ResponseReadingsInnerFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function ReadingGet200ResponseToJSON(json: any): ReadingGet200Response {
    return ReadingGet200ResponseToJSONTyped(json, false);
}

export function ReadingGet200ResponseToJSONTyped(value?: ReadingGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'readings': ((value['readings'] as Array<any>).map(ReadingGet200ResponseReadingsInnerToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

