/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadingPost200Response
 */
export interface ReadingPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ReadingPost200Response
     */
    readingId: number;
}

/**
 * Check if a given object implements the ReadingPost200Response interface.
 */
export function instanceOfReadingPost200Response(value: object): value is ReadingPost200Response {
    if (!('readingId' in value) || value['readingId'] === undefined) return false;
    return true;
}

export function ReadingPost200ResponseFromJSON(json: any): ReadingPost200Response {
    return ReadingPost200ResponseFromJSONTyped(json, false);
}

export function ReadingPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadingPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'readingId': json['reading_id'],
    };
}

export function ReadingPost200ResponseToJSON(json: any): ReadingPost200Response {
    return ReadingPost200ResponseToJSONTyped(json, false);
}

export function ReadingPost200ResponseToJSONTyped(value?: ReadingPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reading_id': value['readingId'],
    };
}

