/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadingGet200ResponseReadingsInner
 */
export interface ReadingGet200ResponseReadingsInner {
    /**
     * 
     * @type {number}
     * @memberof ReadingGet200ResponseReadingsInner
     */
    readingId: number;
    /**
     * 
     * @type {Date}
     * @memberof ReadingGet200ResponseReadingsInner
     */
    recordedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ReadingGet200ResponseReadingsInner
     */
    dayOfWeek: ReadingGet200ResponseReadingsInnerDayOfWeekEnum;
    /**
     * 
     * @type {string}
     * @memberof ReadingGet200ResponseReadingsInner
     */
    status: ReadingGet200ResponseReadingsInnerStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ReadingGet200ResponseReadingsInner
     */
    machineId: number;
    /**
     * 
     * @type {number}
     * @memberof ReadingGet200ResponseReadingsInner
     */
    attributeId: number;
    /**
     * 
     * @type {string}
     * @memberof ReadingGet200ResponseReadingsInner
     */
    attributeValue: string;
}


/**
 * @export
 */
export const ReadingGet200ResponseReadingsInnerDayOfWeekEnum = {
    Sunday: 'SUNDAY',
    Monday: 'MONDAY',
    Tuesday: 'TUESDAY',
    Wednesday: 'WEDNESDAY',
    Thursday: 'THURSDAY',
    Friday: 'FRIDAY',
    Saturday: 'SATURDAY'
} as const;
export type ReadingGet200ResponseReadingsInnerDayOfWeekEnum = typeof ReadingGet200ResponseReadingsInnerDayOfWeekEnum[keyof typeof ReadingGet200ResponseReadingsInnerDayOfWeekEnum];

/**
 * @export
 */
export const ReadingGet200ResponseReadingsInnerStatusEnum = {
    Strange: 'STRANGE',
    Normal: 'NORMAL',
    Alert: 'ALERT',
    Dangerous: 'DANGEROUS',
    Critical: 'CRITICAL'
} as const;
export type ReadingGet200ResponseReadingsInnerStatusEnum = typeof ReadingGet200ResponseReadingsInnerStatusEnum[keyof typeof ReadingGet200ResponseReadingsInnerStatusEnum];


/**
 * Check if a given object implements the ReadingGet200ResponseReadingsInner interface.
 */
export function instanceOfReadingGet200ResponseReadingsInner(value: object): value is ReadingGet200ResponseReadingsInner {
    if (!('readingId' in value) || value['readingId'] === undefined) return false;
    if (!('recordedAt' in value) || value['recordedAt'] === undefined) return false;
    if (!('dayOfWeek' in value) || value['dayOfWeek'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('machineId' in value) || value['machineId'] === undefined) return false;
    if (!('attributeId' in value) || value['attributeId'] === undefined) return false;
    if (!('attributeValue' in value) || value['attributeValue'] === undefined) return false;
    return true;
}

export function ReadingGet200ResponseReadingsInnerFromJSON(json: any): ReadingGet200ResponseReadingsInner {
    return ReadingGet200ResponseReadingsInnerFromJSONTyped(json, false);
}

export function ReadingGet200ResponseReadingsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadingGet200ResponseReadingsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'readingId': json['reading_id'],
        'recordedAt': (new Date(json['recorded_at'])),
        'dayOfWeek': json['day_of_week'],
        'status': json['status'],
        'machineId': json['machine_id'],
        'attributeId': json['attribute_id'],
        'attributeValue': json['attribute_value'],
    };
}

export function ReadingGet200ResponseReadingsInnerToJSON(json: any): ReadingGet200ResponseReadingsInner {
    return ReadingGet200ResponseReadingsInnerToJSONTyped(json, false);
}

export function ReadingGet200ResponseReadingsInnerToJSONTyped(value?: ReadingGet200ResponseReadingsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reading_id': value['readingId'],
        'recorded_at': ((value['recordedAt']).toISOString()),
        'day_of_week': value['dayOfWeek'],
        'status': value['status'],
        'machine_id': value['machineId'],
        'attribute_id': value['attributeId'],
        'attribute_value': value['attributeValue'],
    };
}

