/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReadingGet200ResponseReadingsInner } from './ReadingGet200ResponseReadingsInner';
import {
    ReadingGet200ResponseReadingsInnerFromJSON,
    ReadingGet200ResponseReadingsInnerFromJSONTyped,
    ReadingGet200ResponseReadingsInnerToJSON,
    ReadingGet200ResponseReadingsInnerToJSONTyped,
} from './ReadingGet200ResponseReadingsInner';

/**
 * 
 * @export
 * @interface ReadingIdGet200Response
 */
export interface ReadingIdGet200Response {
    /**
     * 
     * @type {ReadingGet200ResponseReadingsInner}
     * @memberof ReadingIdGet200Response
     */
    reading: ReadingGet200ResponseReadingsInner;
}

/**
 * Check if a given object implements the ReadingIdGet200Response interface.
 */
export function instanceOfReadingIdGet200Response(value: object): value is ReadingIdGet200Response {
    if (!('reading' in value) || value['reading'] === undefined) return false;
    return true;
}

export function ReadingIdGet200ResponseFromJSON(json: any): ReadingIdGet200Response {
    return ReadingIdGet200ResponseFromJSONTyped(json, false);
}

export function ReadingIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadingIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'reading': ReadingGet200ResponseReadingsInnerFromJSON(json['reading']),
    };
}

export function ReadingIdGet200ResponseToJSON(json: any): ReadingIdGet200Response {
    return ReadingIdGet200ResponseToJSONTyped(json, false);
}

export function ReadingIdGet200ResponseToJSONTyped(value?: ReadingIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reading': ReadingGet200ResponseReadingsInnerToJSON(value['reading']),
    };
}

