/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleGet200ResponseRolesInner } from './RoleGet200ResponseRolesInner';
import {
    RoleGet200ResponseRolesInnerFromJSON,
    RoleGet200ResponseRolesInnerFromJSONTyped,
    RoleGet200ResponseRolesInnerToJSON,
    RoleGet200ResponseRolesInnerToJSONTyped,
} from './RoleGet200ResponseRolesInner';

/**
 * 
 * @export
 * @interface RoleIdGet200Response
 */
export interface RoleIdGet200Response {
    /**
     * 
     * @type {RoleGet200ResponseRolesInner}
     * @memberof RoleIdGet200Response
     */
    role: RoleGet200ResponseRolesInner;
}

/**
 * Check if a given object implements the RoleIdGet200Response interface.
 */
export function instanceOfRoleIdGet200Response(value: object): value is RoleIdGet200Response {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function RoleIdGet200ResponseFromJSON(json: any): RoleIdGet200Response {
    return RoleIdGet200ResponseFromJSONTyped(json, false);
}

export function RoleIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'role': RoleGet200ResponseRolesInnerFromJSON(json['role']),
    };
}

export function RoleIdGet200ResponseToJSON(json: any): RoleIdGet200Response {
    return RoleIdGet200ResponseToJSONTyped(json, false);
}

export function RoleIdGet200ResponseToJSONTyped(value?: RoleIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': RoleGet200ResponseRolesInnerToJSON(value['role']),
    };
}

