/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleGet200ResponseRolesInner } from './RoleGet200ResponseRolesInner';
import {
    RoleGet200ResponseRolesInnerFromJSON,
    RoleGet200ResponseRolesInnerFromJSONTyped,
    RoleGet200ResponseRolesInnerToJSON,
    RoleGet200ResponseRolesInnerToJSONTyped,
} from './RoleGet200ResponseRolesInner';

/**
 * 
 * @export
 * @interface RoleGet200Response
 */
export interface RoleGet200Response {
    /**
     * 
     * @type {Array<RoleGet200ResponseRolesInner>}
     * @memberof RoleGet200Response
     */
    roles: Array<RoleGet200ResponseRolesInner>;
    /**
     * 
     * @type {number}
     * @memberof RoleGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof RoleGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof RoleGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the RoleGet200Response interface.
 */
export function instanceOfRoleGet200Response(value: object): value is RoleGet200Response {
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function RoleGet200ResponseFromJSON(json: any): RoleGet200Response {
    return RoleGet200ResponseFromJSONTyped(json, false);
}

export function RoleGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'roles': ((json['roles'] as Array<any>).map(RoleGet200ResponseRolesInnerFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function RoleGet200ResponseToJSON(json: any): RoleGet200Response {
    return RoleGet200ResponseToJSONTyped(json, false);
}

export function RoleGet200ResponseToJSONTyped(value?: RoleGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roles': ((value['roles'] as Array<any>).map(RoleGet200ResponseRolesInnerToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

