/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RolePost200Response
 */
export interface RolePost200Response {
    /**
     * 
     * @type {string}
     * @memberof RolePost200Response
     */
    userRoleId: string;
}

/**
 * Check if a given object implements the RolePost200Response interface.
 */
export function instanceOfRolePost200Response(value: object): value is RolePost200Response {
    if (!('userRoleId' in value) || value['userRoleId'] === undefined) return false;
    return true;
}

export function RolePost200ResponseFromJSON(json: any): RolePost200Response {
    return RolePost200ResponseFromJSONTyped(json, false);
}

export function RolePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RolePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'userRoleId': json['user_role_id'],
    };
}

export function RolePost200ResponseToJSON(json: any): RolePost200Response {
    return RolePost200ResponseToJSONTyped(json, false);
}

export function RolePost200ResponseToJSONTyped(value?: RolePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_role_id': value['userRoleId'],
    };
}

