/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleGet200ResponseRolesInner
 */
export interface RoleGet200ResponseRolesInner {
    /**
     * 
     * @type {number}
     * @memberof RoleGet200ResponseRolesInner
     */
    roleId: number;
    /**
     * 
     * @type {string}
     * @memberof RoleGet200ResponseRolesInner
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof RoleGet200ResponseRolesInner
     */
    description: string | null;
}

/**
 * Check if a given object implements the RoleGet200ResponseRolesInner interface.
 */
export function instanceOfRoleGet200ResponseRolesInner(value: object): value is RoleGet200ResponseRolesInner {
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function RoleGet200ResponseRolesInnerFromJSON(json: any): RoleGet200ResponseRolesInner {
    return RoleGet200ResponseRolesInnerFromJSONTyped(json, false);
}

export function RoleGet200ResponseRolesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleGet200ResponseRolesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'roleId': json['role_id'],
        'role': json['role'],
        'description': json['description'],
    };
}

export function RoleGet200ResponseRolesInnerToJSON(json: any): RoleGet200ResponseRolesInner {
    return RoleGet200ResponseRolesInnerToJSONTyped(json, false);
}

export function RoleGet200ResponseRolesInnerToJSONTyped(value?: RoleGet200ResponseRolesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role_id': value['roleId'],
        'role': value['role'],
        'description': value['description'],
    };
}

