/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserGet200ResponseUsersInner
 */
export interface UserGet200ResponseUsersInner {
    /**
     * 
     * @type {number}
     * @memberof UserGet200ResponseUsersInner
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof UserGet200ResponseUsersInner
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserGet200ResponseUsersInner
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserGet200ResponseUsersInner
     */
    passwordHash: string;
    /**
     * 
     * @type {Date}
     * @memberof UserGet200ResponseUsersInner
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserGet200ResponseUsersInner
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UserGet200ResponseUsersInner interface.
 */
export function instanceOfUserGet200ResponseUsersInner(value: object): value is UserGet200ResponseUsersInner {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('passwordHash' in value) || value['passwordHash'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserGet200ResponseUsersInnerFromJSON(json: any): UserGet200ResponseUsersInner {
    return UserGet200ResponseUsersInnerFromJSONTyped(json, false);
}

export function UserGet200ResponseUsersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGet200ResponseUsersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'username': json['username'],
        'email': json['email'],
        'passwordHash': json['password_hash'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function UserGet200ResponseUsersInnerToJSON(json: any): UserGet200ResponseUsersInner {
    return UserGet200ResponseUsersInnerToJSONTyped(json, false);
}

export function UserGet200ResponseUsersInnerToJSONTyped(value?: UserGet200ResponseUsersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'username': value['username'],
        'email': value['email'],
        'password_hash': value['passwordHash'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

