/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRolePost201ResponseUserRole
 */
export interface UserRolePost201ResponseUserRole {
    /**
     * 
     * @type {number}
     * @memberof UserRolePost201ResponseUserRole
     */
    userRoleId: number;
    /**
     * 
     * @type {number}
     * @memberof UserRolePost201ResponseUserRole
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof UserRolePost201ResponseUserRole
     */
    roleId: number;
}

/**
 * Check if a given object implements the UserRolePost201ResponseUserRole interface.
 */
export function instanceOfUserRolePost201ResponseUserRole(value: object): value is UserRolePost201ResponseUserRole {
    if (!('userRoleId' in value) || value['userRoleId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    return true;
}

export function UserRolePost201ResponseUserRoleFromJSON(json: any): UserRolePost201ResponseUserRole {
    return UserRolePost201ResponseUserRoleFromJSONTyped(json, false);
}

export function UserRolePost201ResponseUserRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRolePost201ResponseUserRole {
    if (json == null) {
        return json;
    }
    return {
        
        'userRoleId': json['user_role_id'],
        'userId': json['user_id'],
        'roleId': json['role_id'],
    };
}

export function UserRolePost201ResponseUserRoleToJSON(json: any): UserRolePost201ResponseUserRole {
    return UserRolePost201ResponseUserRoleToJSONTyped(json, false);
}

export function UserRolePost201ResponseUserRoleToJSONTyped(value?: UserRolePost201ResponseUserRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_role_id': value['userRoleId'],
        'user_id': value['userId'],
        'role_id': value['roleId'],
    };
}

