/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserIdPutRequest
 */
export interface UserIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof UserIdPutRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserIdPutRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserIdPutRequest
     */
    passwordHash?: string;
}

/**
 * Check if a given object implements the UserIdPutRequest interface.
 */
export function instanceOfUserIdPutRequest(value: object): value is UserIdPutRequest {
    return true;
}

export function UserIdPutRequestFromJSON(json: any): UserIdPutRequest {
    return UserIdPutRequestFromJSONTyped(json, false);
}

export function UserIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'passwordHash': json['password_hash'] == null ? undefined : json['password_hash'],
    };
}

export function UserIdPutRequestToJSON(json: any): UserIdPutRequest {
    return UserIdPutRequestToJSONTyped(json, false);
}

export function UserIdPutRequestToJSONTyped(value?: UserIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'email': value['email'],
        'password_hash': value['passwordHash'],
    };
}

