/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRolePost201ResponseUserRole } from './UserRolePost201ResponseUserRole';
import {
    UserRolePost201ResponseUserRoleFromJSON,
    UserRolePost201ResponseUserRoleFromJSONTyped,
    UserRolePost201ResponseUserRoleToJSON,
    UserRolePost201ResponseUserRoleToJSONTyped,
} from './UserRolePost201ResponseUserRole';

/**
 * 
 * @export
 * @interface UserRolePost201Response
 */
export interface UserRolePost201Response {
    /**
     * 
     * @type {UserRolePost201ResponseUserRole}
     * @memberof UserRolePost201Response
     */
    userRole: UserRolePost201ResponseUserRole;
}

/**
 * Check if a given object implements the UserRolePost201Response interface.
 */
export function instanceOfUserRolePost201Response(value: object): value is UserRolePost201Response {
    if (!('userRole' in value) || value['userRole'] === undefined) return false;
    return true;
}

export function UserRolePost201ResponseFromJSON(json: any): UserRolePost201Response {
    return UserRolePost201ResponseFromJSONTyped(json, false);
}

export function UserRolePost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRolePost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'userRole': UserRolePost201ResponseUserRoleFromJSON(json['userRole']),
    };
}

export function UserRolePost201ResponseToJSON(json: any): UserRolePost201Response {
    return UserRolePost201ResponseToJSONTyped(json, false);
}

export function UserRolePost201ResponseToJSONTyped(value?: UserRolePost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userRole': UserRolePost201ResponseUserRoleToJSON(value['userRole']),
    };
}

