/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGet200ResponseUsersInner } from './UserGet200ResponseUsersInner';
import {
    UserGet200ResponseUsersInnerFromJSON,
    UserGet200ResponseUsersInnerFromJSONTyped,
    UserGet200ResponseUsersInnerToJSON,
    UserGet200ResponseUsersInnerToJSONTyped,
} from './UserGet200ResponseUsersInner';

/**
 * 
 * @export
 * @interface UserIdGet200Response
 */
export interface UserIdGet200Response {
    /**
     * 
     * @type {UserGet200ResponseUsersInner}
     * @memberof UserIdGet200Response
     */
    user: UserGet200ResponseUsersInner;
}

/**
 * Check if a given object implements the UserIdGet200Response interface.
 */
export function instanceOfUserIdGet200Response(value: object): value is UserIdGet200Response {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function UserIdGet200ResponseFromJSON(json: any): UserIdGet200Response {
    return UserIdGet200ResponseFromJSONTyped(json, false);
}

export function UserIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserGet200ResponseUsersInnerFromJSON(json['user']),
    };
}

export function UserIdGet200ResponseToJSON(json: any): UserIdGet200Response {
    return UserIdGet200ResponseToJSONTyped(json, false);
}

export function UserIdGet200ResponseToJSONTyped(value?: UserIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserGet200ResponseUsersInnerToJSON(value['user']),
    };
}

