/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGet200ResponseUsersInner } from './UserGet200ResponseUsersInner';
import {
    UserGet200ResponseUsersInnerFromJSON,
    UserGet200ResponseUsersInnerFromJSONTyped,
    UserGet200ResponseUsersInnerToJSON,
    UserGet200ResponseUsersInnerToJSONTyped,
} from './UserGet200ResponseUsersInner';

/**
 * 
 * @export
 * @interface UserGet200Response
 */
export interface UserGet200Response {
    /**
     * 
     * @type {Array<UserGet200ResponseUsersInner>}
     * @memberof UserGet200Response
     */
    users: Array<UserGet200ResponseUsersInner>;
    /**
     * 
     * @type {number}
     * @memberof UserGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof UserGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof UserGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the UserGet200Response interface.
 */
export function instanceOfUserGet200Response(value: object): value is UserGet200Response {
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function UserGet200ResponseFromJSON(json: any): UserGet200Response {
    return UserGet200ResponseFromJSONTyped(json, false);
}

export function UserGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(UserGet200ResponseUsersInnerFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function UserGet200ResponseToJSON(json: any): UserGet200Response {
    return UserGet200ResponseToJSONTyped(json, false);
}

export function UserGet200ResponseToJSONTyped(value?: UserGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': ((value['users'] as Array<any>).map(UserGet200ResponseUsersInnerToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

