/* tslint:disable */
/* eslint-disable */
/**
 * Nextron API
 * API for managing machines, users, and AI models in Nextron
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRolePostRequest
 */
export interface UserRolePostRequest {
    /**
     * 
     * @type {number}
     * @memberof UserRolePostRequest
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof UserRolePostRequest
     */
    roleId: number;
}

/**
 * Check if a given object implements the UserRolePostRequest interface.
 */
export function instanceOfUserRolePostRequest(value: object): value is UserRolePostRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    return true;
}

export function UserRolePostRequestFromJSON(json: any): UserRolePostRequest {
    return UserRolePostRequestFromJSONTyped(json, false);
}

export function UserRolePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRolePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'roleId': json['role_id'],
    };
}

export function UserRolePostRequestToJSON(json: any): UserRolePostRequest {
    return UserRolePostRequestToJSONTyped(json, false);
}

export function UserRolePostRequestToJSONTyped(value?: UserRolePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'role_id': value['roleId'],
    };
}

